In [ ]:
from google.colab import files
files.upload()

TypeError: 'NoneType' object is not subscriptable

In [ ]:
import os
os.listdir('/content/sample_data')

In [ ]:
import pandas as pd
file_path ="/content/indian_engineering_student_placement[1].csv"
df = pd.read_csv(file_path)
print(df.to_string())

      Student_ID  gender branch   cgpa  tenth_percentage  twelfth_percentage  backlogs  study_hours_per_day  attendance_percentage  projects_completed  internships_completed  coding_skill_rating  communication_skill_rating  aptitude_skill_rating  hackathons_participated  certifications_count  sleep_hours  stress_level part_time_job family_income_level city_tier internet_access extracurricular_involvement
0              1    Male    ECE   8.74              74.0                75.0         0                  3.8                   71.1                   7                      3                    4                           2                      5                        4                     5          6.5             8           Yes              Medium    Tier 2             Yes                      Medium
1              2  Female    ECE   7.80              75.3                69.7         0                  6.3                   69.5                   5                      1                    3                           4                      3                        4                     1          7.1             8           Yes              Medium    Tier 3             Yes                         Low
2              3  Female     IT   6.95              62.8                68.3         0                  1.5                   62.5                   8                      2                    5                           1                      4                        6                     3          6.1             2            No                 Low    Tier 2             Yes                        High
3              4    Male    ECE   7.46              57.9                51.4         1                  4.7                   64.6                   6                      2                    3                           1                      4                        2                     2          7.3             7            No              Medium    Tier 1             Yes                         Low
4              5    Male     IT   6.86              61.3                73.5         2                  5.2                   75.9                   3                      3                    2                           5                      3                        2                     1          6.0             7            No              Medium    Tier 1             Yes                      Medium
5              6    Male    CSE   7.46              70.5                70.4         3                  3.6                   81.7                   5                      3                    3                           5                      4                        2                     2          8.8            10           Yes                High    Tier 1             Yes                      Medium
6              7    Male     CE   8.26              81.2                74.8         0                  1.8                   59.6                   4                      1                    3                           1                      3                        4                     4          5.7             8            No                 Low    Tier 1              No                        High
7              8  Female     IT   7.01              63.9                61.2         0                  2.4                   64.7                   7                      1                    4                           1                      4                        4                     5          4.2            10            No              Medium    Tier 2             Yes                         Low
8              9  Female    CSE   7.97              71.4                73.8         1                  7.6                   75.5                   7                      2                    4                           5                      4                        5                     7          5.4            10            No              Medium    Tier 2             Yes                      Medium
9             10  Female    ECE   8.79              70.1                77.1         0                  5.9                   77.2                   7                      4                    4                           1                      4                        4                     3          7.5            10           Yes              Medium    Tier 1             Yes                         Low
10            11    Male    CSE   6.77              62.6                61.7         0                  5.2                   76.7                   4                      0                    3                           1                      3                        3                     4          6.9             3            No                High    Tier 1             Yes                         Low
11            12  Female     CE   9.62              83.4                86.8         0                  8.3                   75.1                   8                      3                    5                           4                      5                        5                     7          7.9             8            No              Medium    Tier 1             Yes                        High
12            13  Female    ECE   8.17              72.1                71.3         0                  2.4                   70.7                   7                      1                    4                           1                      5                        4                     4          7.6             4            No                High    Tier 3             Yes                        High
13            14    Male     ME   8.94              84.9                81.7         0                  4.0                   70.8                   2                      3                    2                           3                      4                        2                     1          6.2             2           Yes              Medium    Tier 2             Yes                      Medium
14            15    Male    CSE   8.13              75.9                70.3         0                  4.1                   71.3                   8                      1                    5                           3                      4                        4                     7          6.4             8           Yes              Medium    Tier 3             Yes                         Low
15            16    Male    CSE   8.57              79.5                79.0         1                  6.5                   74.2                   7                      3                    5                           4                      4                        6                     3          6.5             3            No                 Low    Tier 3             Yes                        High
16            17    Male    CSE   8.97              76.3                84.0         0                  0.7                   62.5                   7                      4                    5                           1                      4                        6                     2          9.0             4            No                 Low    Tier 2             Yes                         NaN
17            18    Male    ECE   8.14              66.2                83.0         0                  4.2                   80.7                   2                      2                    1                           4                      4                        1                     1          7.8             3            No                 Low    Tier 3              No                         NaN
18            19    Male     ME   9.06              78.0                82.3         0                  4.0                   76.1                   8                      2                    5                           1                      5                        6                     4          9.0             6            No                 Low    Tier 1             Yes                      Medium
19            20    Male     IT   9.44              78.7                96.4         0                  5.6                   81.1                   7                      3                    5                           1                      4                        4                     6          8.0            10            No                 Low    Tier 2             Yes                         Low
20            21  Female     ME   7.22              70.4                67.8         1                  3.1                   62.8                   3                      1                    3                           1                      5                        2                     3          6.9             2           Yes                 Low    Tier 1             Yes                        High
21            22    Male    ECE   7.75              70.7                70.9         2                  6.4                   91.2                   3                      2                    2                           3                      4                        1                     1          5.8            10            No                 Low    Tier 3             Yes                         Low
22            23    Male     IT   7.60              77.7                64.1         0                  4.8                   72.0                   8                      2                    5                           3                      5                        3                     2          7.2             7            No                High    Tier 1             Yes                         Low
23            24    Male     CE   7.56              70.3                67.0         0                  2.4                   70.3                   7                      3                    5                           2                      4                        5                     6          6.9            10            No                 Low    Tier 3             Yes                      Medium
24            25    Male     IT   8.59              84.4                82.7         0                  5.2                   76.3                   5                      3                    4                           4                      4                        4                     5          6.9             8            No              Medium    Tier 1             Yes                      Medium
25            26  Female    ECE   7.57              70.3                62.5         2                  3.8                   72.2                   6                      1                    4                           5                      4                        4                     1          6.7             3            No                 Low    Tier 3             Yes                         Low
26            27    Male    CSE   7.37              71.9                62.6         0                  5.0                   79.4                   4                      0                    2                           4                      4                        2                     2          4.5            10            No                High    Tier 2             Yes                         Low
27            28    Male    CSE   7.91              71.3                71.1         0                  1.6                   70.2                   2                      1                    2                           4                      3                        3                     5          8.5             2            No                High    Tier 2             Yes                      Medium
28            29    Male     CE   8.98              87.1                80.5         0                  3.5                   62.6                   7                      3                    5                           3                      4                        5                     3          6.9            10           Yes              Medium    Tier 2             Yes                         Low
29            30    Male    CSE   7.85              75.0                76.3         0                  6.0                   70.9                   8                      1                    5                           1                      4                        3                     0          5.3            10            No              Medium    Tier 2             Yes                         NaN
30            31  Female    ECE   8.74              71.7                84.8         0                  6.8                   79.8                   2                      1                    2                           4                      4                        1                     0          7.6             9            No                 Low    Tier 2             Yes                      Medium
31            32    Male    ECE   8.19              78.2                67.9         0                  4.9                   77.2                   5                      2                    3                           4                      4                        5                     1          6.0             5            No                High    Tier 3             Yes                         NaN
32            33    Male     ME   8.20              77.2                77.9         0                  3.5                   70.8                   3                      1                    2                           4                      4                        1                     2          7.7             6            No                High    Tier 1             Yes                        High
33            34  Female     ME   7.77              60.3                67.5         0                  2.9                   64.0                   8                      2                    5                           2                      5                        6                     5          8.1             2            No                High    Tier 3             Yes                      Medium
34            35  Female    CSE   5.81              51.6                53.8         0                  2.6                   71.9                   3                      0                    2                           3                      3                        3                     2          8.2             5            No              Medium    Tier 2             Yes                        High
35            36  Female    ECE   7.49              72.7                67.0         0                  2.6                   75.5                   3                      2                    2                           3                      4                        2                     2          6.8             6            No              Medium    Tier 3             Yes                         Low
36            37    Male     ME   8.35              64.3                79.1         0                  2.3                   66.2                   5                      3                    3                           2                      4                        2                     1          6.5             5            No                High    Tier 2             Yes                        High
37            38    Male     IT   8.45              79.4                65.9         0                  3.8                   73.9                   8                      2                    5                           2                      4                        5                     3          6.2             4            No                 Low    Tier 2             Yes                         NaN
38            39  Female     CE   8.72              80.3                76.8         0                  2.8                   60.5                   8                      4                    5                           2                      5                        3                     4          6.1             8            No              Medium    Tier 3             Yes                         NaN
39            40    Male     IT   7.24              65.4                72.7         0                  5.1                   73.5                   4                      2                    2                           2                      4                        3                     2          7.0             2            No                 Low    Tier 2             Yes                         NaN
40            41    Male     CE   9.06              97.4                81.1         0                  4.7                   77.4                   7                      3                    5                           3                      4                        5                     4          6.7             1            No                High    Tier 2             Yes                         Low
41            42    Male     ME   8.28              78.1                62.8         1                  6.2                   79.2                   2                      2                    2                           2                      4                        4                     4          6.0             2            No                 Low    Tier 1             Yes                         NaN
42            43    Male    CSE   7.68              66.4                65.6         1                  5.1                   71.3                   8                      2                    5                           3                      4                        6                     3          5.6             6            No                 Low    Tier 1             Yes                      Medium
43            44  Female     ME   9.32              82.4                89.1         0                  5.7                   75.5                   5                      3                    3                           1                      5                        1                     1          6.9             2           Yes              Medium    Tier 2             Yes                         Low
44            45    Male     ME   8.68              82.6                72.6         0                  2.4                   71.5                   7                      3                    4                           4                      4                        4                     1          6.5            10           Yes              Medium    Tier 3             Yes                         Low
45            46  Female     ME   9.68              90.2                84.5         0                  5.0                   73.5                   5                      3                    5                           5                      5                        3                     2          5.6             4           Yes              Medium    Tier 2             Yes                      Medium
46            47    Male    ECE   9.03              80.0                84.2         0                  4.5                   70.8                   8                      2                    4                           3                      4                        5                     1          8.0             6           Yes                 Low    Tier 1             Yes                         NaN
47            48    Male    ECE   7.66              74.0                70.4         0                  0.1                   62.3                   4                      1                    3                           3                      3                        2                     3          9.0             8            No                 Low    Tier 2             Yes                      Medium

In [ ]:
import pandas as pd
file_path ="/content/indian_engineering_student_placement[1].csv"
df = pd.read_csv(file_path)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Student_ID                   5000 non-null   int64
 1   gender                       5000 non-null   object
 2   branch                       5000 non-null   object
 3   cgpa                         5000 non-null   float64
 4   tenth_percentage             5000 non-null   float64
 5   twelfth_percentage           5000 non-null   float64
 6   backlogs                     5000 non-null   int64
 7   study_hours_per_day          5000 non-null   float64
 8   attendance_percentage        5000 non-null   float64
 9   projects_completed           5000 non-null   int64
 10  internships_completed        5000 non-null   int64
 11  coding_skill_rating          5000 non-null   int64
 12  communication_skill_rating   5000 non-null   int64
 13  aptitude_skill_rating        5000 non-null   int64
 14  hackathons_participated      5000 non-null   int64
 15  certifications_count         5000 non-null   int64
 16  sleep_hours                  5000 non-null   float64
 17  stress_level                 5000 non-null   int64
 18  part_time_job                5000 non-null   object
 19  family_income_level          5000 non-null   object
 20  city_tier                    5000 non-null   object
 21  internet_access              5000 non-null   object
 22  extracurricular_involvement  3994 non-null   object
dtypes: float64(6), int64(10), object(7)
memory usage: 898.6+ KB
None

In [ ]:
import pandas as pd
file_path ="/content/indian_engineering_student_placement[1].csv"
df = pd.read_csv(file_path)
df.head()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,aptitude_skill_rating,hackathons_participated,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement
0,1,Male,ECE,8.74,74.0,75.0,0,3.8,71.1,7,...,5,4,5,6.5,8,Yes,Medium,Tier 2,Yes,Medium
1,2,Female,ECE,7.80,75.3,69.7,0,6.3,69.5,5,...,3,4,1,7.1,8,Yes,Medium,Tier 3,Yes,Low
2,3,Female,IT,6.95,62.8,68.3,0,1.5,62.5,8,...,4,6,3,6.1,2,No,Low,Tier 2,Yes,High
3,4,Male,ECE,7.46,57.9,51.4,1,4.7,64.6,6,...,4,2,2,7.3,7,No,Medium,Tier 1,Yes,Low
4,5,Male,IT,6.86,61.3,73.5,2,5.2,75.9,3,...,3,2,1,6.0,7,No,Medium,Tier 1,Yes,Medium

In [ ]:
import pandas as pd
file_path ="/content/indian_engineering_student_placement[1].csv"
df = pd.read_csv(file_path)
df.tail()

,Student_ID,gender,branch,cgpa,tenth_percentage,twelfth_percentage,backlogs,study_hours_per_day,attendance_percentage,projects_completed,...,aptitude_skill_rating,hackathons_participated,certifications_count,sleep_hours,stress_level,part_time_job,family_income_level,city_tier,internet_access,extracurricular_involvement
4995,4996,Female,IT,10.00,90.4,98.3,0,3.7,75.3,6,...,5,4,2,7.3,2,No,Medium,Tier 3,Yes,Low
4996,4997,Male,IT,7.76,74.3,72.6,2,6.3,72.3,4,...,4,3,2,7.8,6,No,Low,Tier 1,Yes,Low
4997,4998,Male,IT,7.79,64.0,71.2,2,2.0,63.8,6,...,4,6,2,6.1,5,Yes,Low,Tier 2,No,Medium
4998,4999,Female,ECE,8.76,74.3,74.0,0,5.1,72.0,6,...,4,4,5,9.0,10,No,Medium,Tier 2,Yes,High
4999,5000,Male,CSE,9.45,85.6,80.0,0,2.8,63.4,8,...,4,6,2,7.8,1,No,Low,Tier 1,No,High

In [ ]:
import pandas as pd
file_path ="/content/indian_engineering_student_placement[1].csv"
df = pd.read_csv(file_path)
print(df)